[2025-09-10T18:46:10.117+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.evaluate_model scheduled__2025-09-09T00:00:00+00:00 [queued]>
[2025-09-10T18:46:10.140+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.evaluate_model scheduled__2025-09-09T00:00:00+00:00 [queued]>
[2025-09-10T18:46:10.141+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-10T18:46:10.256+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): evaluate_model> on 2025-09-09 00:00:00+00:00
[2025-09-10T18:46:10.270+0000] {standard_task_runner.py:60} INFO - Started process 636 to run task
[2025-09-10T18:46:10.285+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'evaluate_model', 'scheduled__2025-09-09T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpej38j293']
[2025-09-10T18:46:10.290+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask evaluate_model
[2025-09-10T18:46:10.472+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.evaluate_model scheduled__2025-09-09T00:00:00+00:00 [running]> on host 2b772f5c8fa1
[2025-09-10T18:46:10.713+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='evaluate_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-09T00:00:00+00:00'
[2025-09-10T18:46:10.857+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-apps:latest
[2025-09-10T18:46:28.270+0000] {docker.py:429} INFO - /usr/local/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.4.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[2025-09-10T18:46:28.569+0000] {docker.py:429} INFO - /usr/local/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.4.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[2025-09-10T18:46:28.665+0000] {docker.py:429} INFO - /usr/local/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.4.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[2025-09-10T18:46:28.668+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/script/evaluate.py", line 81, in <module>
[2025-09-10T18:46:28.671+0000] {docker.py:429} INFO - === MODEL EVALUATION ===

1. Loading the test dataset...
Loaded 942 rows and 23 columns
Loaded 942 rows and 1 columns
[2025-09-10T18:46:28.673+0000] {docker.py:429} INFO - main()
  File "/app/script/evaluate.py", line 51, in main
    reports = joblib.load(Path(__file__).parent.parent / 'metrics' / 'Report.joblib')
[2025-09-10T18:46:28.676+0000] {docker.py:429} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 749, in load
    obj = _unpickle(
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 626, in _unpickle
[2025-09-10T18:46:28.679+0000] {docker.py:429} INFO - obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pickle.py", line 1256, in load
[2025-09-10T18:46:28.685+0000] {docker.py:429} INFO - dispatch[key[0]](self)
  File "/usr/local/lib/python3.12/pickle.py", line 1581, in load_stack_global
[2025-09-10T18:46:28.687+0000] {docker.py:429} INFO - self.append(self.find_class(module, name))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pickle.py", line 1624, in find_class
    return _getattribute(sys.modules[module], name)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pickle.py", line 326, in _getattribute
[2025-09-10T18:46:28.692+0000] {docker.py:429} INFO - raise AttributeError("Can't get attribute {!r} on {!r}"
AttributeError: Can't get attribute '__pyx_unpickle_CyHalfBinomialLoss' on <module 'sklearn._loss._loss' from '/usr/local/lib/python3.12/site-packages/sklearn/_loss/_loss.cpython-312-x86_64-linux-gnu.so'>
[2025-09-10T18:46:34.406+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-09-10T18:46:34.425+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_orchestration, task_id=evaluate_model, execution_date=20250909T000000, start_date=20250910T184610, end_date=20250910T184634
[2025-09-10T18:46:34.691+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 72 for task evaluate_model (Docker container failed: {'StatusCode': 1}; 636)
[2025-09-10T18:46:34.718+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-10T18:46:34.784+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
