[2025-09-01T05:05:11.278+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:59:33.548093+00:00 [queued]>
[2025-09-01T05:05:11.294+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:59:33.548093+00:00 [queued]>
[2025-09-01T05:05:11.295+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-01T05:05:11.355+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): train_model> on 2025-09-01 04:59:33.548093+00:00
[2025-09-01T05:05:11.362+0000] {standard_task_runner.py:60} INFO - Started process 956 to run task
[2025-09-01T05:05:11.368+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'train_model', 'manual__2025-09-01T04:59:33.548093+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpb0y_3p_0']
[2025-09-01T05:05:11.372+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask train_model
[2025-09-01T05:05:11.526+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:59:33.548093+00:00 [running]> on host 9f4fe8d13603
[2025-09-01T05:05:11.725+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T04:59:33.548093+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T04:59:33.548093+00:00'
[2025-09-01T05:05:11.775+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-churn-app:latest
[2025-09-01T05:05:20.459+0000] {docker.py:429} INFO - === CUSTOMER CHURN PREDICTION TRAINING ===

1. Loading data...
[2025-09-01T05:05:20.460+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/script/train.py", line 37, in <module>
    main()
  File "/app/script/train.py", line 20, in main
[2025-09-01T05:05:20.466+0000] {docker.py:429} INFO - df = load_data("data/raw/customer_churn.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/data/load_data.py", line 11, in load_data
[2025-09-01T05:05:20.467+0000] {docker.py:429} INFO - raise FileNotFoundError(f"Data file not found: {file_path}")
FileNotFoundError: Data file not found: /app/data/raw/customer_churn.csv
[2025-09-01T05:05:24.481+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-09-01T05:05:24.486+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_orchestration, task_id=train_model, execution_date=20250901T045933, start_date=20250901T050511, end_date=20250901T050524
[2025-09-01T05:05:24.589+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 44 for task train_model (Docker container failed: {'StatusCode': 1}; 956)
[2025-09-01T05:05:24.622+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-01T05:05:24.662+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
