[2025-09-12T00:29:07.493+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.log_experiments scheduled__2025-09-11T00:00:00+00:00 [queued]>
[2025-09-12T00:29:07.514+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.log_experiments scheduled__2025-09-11T00:00:00+00:00 [queued]>
[2025-09-12T00:29:07.515+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-09-12T00:29:07.604+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): log_experiments> on 2025-09-11 00:00:00+00:00
[2025-09-12T00:29:07.620+0000] {standard_task_runner.py:60} INFO - Started process 395 to run task
[2025-09-12T00:29:07.632+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'log_experiments', 'scheduled__2025-09-11T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpefgdk9tx']
[2025-09-12T00:29:07.638+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask log_experiments
[2025-09-12T00:29:07.854+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.log_experiments scheduled__2025-09-11T00:00:00+00:00 [running]> on host 10edecd9c410
[2025-09-12T00:29:08.194+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='log_experiments' AIRFLOW_CTX_EXECUTION_DATE='2025-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-11T00:00:00+00:00'
[2025-09-12T00:29:08.358+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-apps:latest
[2025-09-12T00:29:20.011+0000] {docker.py:429} INFO - /usr/local/lib/python3.12/site-packages/mlflow/utils/requirements_utils.py:20: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources  # noqa: TID251
[2025-09-12T00:30:31.050+0000] {docker.py:429} INFO - 2025/09/12 00:30:30 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-09-12T00:31:19.176+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 137}
[2025-09-12T00:31:19.220+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=ml_pipeline_orchestration, task_id=log_experiments, execution_date=20250911T000000, start_date=20250912T002907, end_date=20250912T003119
[2025-09-12T00:31:19.380+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task log_experiments (Docker container failed: {'StatusCode': 137}; 395)
[2025-09-12T00:31:19.415+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-12T00:31:19.508+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
