[2025-09-01T04:57:05.159+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:51:29.381289+00:00 [queued]>
[2025-09-01T04:57:05.173+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:51:29.381289+00:00 [queued]>
[2025-09-01T04:57:05.174+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-01T04:57:06.295+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): train_model> on 2025-09-01 04:51:29.381289+00:00
[2025-09-01T04:57:06.303+0000] {standard_task_runner.py:60} INFO - Started process 705 to run task
[2025-09-01T04:57:06.309+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'train_model', 'manual__2025-09-01T04:51:29.381289+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpd2hgkobt']
[2025-09-01T04:57:06.313+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask train_model
[2025-09-01T04:57:07.226+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.train_model manual__2025-09-01T04:51:29.381289+00:00 [running]> on host 9f4fe8d13603
[2025-09-01T04:57:10.181+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T04:51:29.381289+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T04:51:29.381289+00:00'
[2025-09-01T04:57:10.241+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-churn-app:latest
[2025-09-01T04:57:45.923+0000] {docker.py:429} INFO - === CUSTOMER CHURN PREDICTION TRAINING ===

1. Loading data...
[2025-09-01T04:57:45.925+0000] {docker.py:429} INFO - Traceback (most recent call last):
  File "/app/script/train.py", line 37, in <module>
    main()
  File "/app/script/train.py", line 20, in main
[2025-09-01T04:57:45.926+0000] {docker.py:429} INFO - df = load_data("data/raw/customer_churn.csv")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/data/load_data.py", line 11, in load_data
[2025-09-01T04:57:45.927+0000] {docker.py:429} INFO - raise FileNotFoundError(f"Data file not found: {file_path}")
FileNotFoundError: Data file not found: /app/data/raw/customer_churn.csv
[2025-09-01T04:58:06.827+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 502, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 376, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 437, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 1}
[2025-09-01T04:58:06.833+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=ml_pipeline_orchestration, task_id=train_model, execution_date=20250901T045129, start_date=20250901T045705, end_date=20250901T045806
[2025-09-01T04:58:07.597+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task train_model (Docker container failed: {'StatusCode': 1}; 705)
[2025-09-01T04:58:07.617+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-01T04:58:08.260+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
