[2025-09-14T09:12:02.730+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [queued]>
[2025-09-14T09:12:02.826+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [queued]>
[2025-09-14T09:12:02.848+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-14T09:12:04.129+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): train_model> on 2025-09-13 00:00:00+00:00
[2025-09-14T09:12:04.292+0000] {standard_task_runner.py:60} INFO - Started process 171 to run task
[2025-09-14T09:12:04.610+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'train_model', 'scheduled__2025-09-13T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpge_b4lmk']
[2025-09-14T09:12:04.670+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask train_model
[2025-09-14T09:12:06.699+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [running]> on host c665ef4223e6
[2025-09-14T09:12:09.709+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-13T00:00:00+00:00'
[2025-09-14T09:12:10.935+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-apps:latest
[2025-09-14T09:13:01.618+0000] {docker.py:429} INFO - /app/src/data/clean_data.py:26: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_by_tenure = df_clean.groupby(pd.cut(df_clean['tenure'], bins=[0, 12, 24, 48, 72]))['total_charges'].median()
[2025-09-14T09:13:05.474+0000] {docker.py:429} INFO - === CUSTOMER CHURN PREDICTION TRAINING ===

1. Loading data...
Loaded 5000 rows and 14 columns

2. Cleaning data...
Starting data cleaning...
Removed 0 duplicate rows
Data cleaning completed
Removed 293 outliers from total_charges
Data cleaning completed. Final shape: (4707, 14)

3. Transforming data...
Starting data transformation...
Fitted encoder for gender
Fitted encoder for contract
Fitted encoder for internet_service
Fitted encoder for online_security
Fitted encoder for tech_support
Fitted encoder for streaming_tv
Fitted encoder for payment_method
Fitted encoder for paperless_billing
Train set: 3765 samples
Test set: 942 samples
All transformers saved to /app/Models/transformers.joblib
Data transformation completed

4. Training models...
Training logistic_regression...
[2025-09-14T09:22:19.278+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-09-14T09:23:46.491+0000] {process_utils.py:131} INFO - Sending 15 to group 171. PIDs of all processes in the group: [171]
[2025-09-14T09:24:02.404+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 171
[2025-09-14T09:24:30.884+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-14T09:24:39.731+0000] {docker.py:521} INFO - Stopping docker container
[2025-09-14T09:25:05.311+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=171, name='airflow task ru', status='sleeping', started='09:12:03') did not respond to SIGTERM. Trying SIGKILL
[2025-09-14T09:25:09.236+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 171
[2025-09-14T09:25:10.060+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=171, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='09:12:03') (171) terminated with exit code -9
[2025-09-14T09:25:10.279+0000] {standard_task_runner.py:175} ERROR - Job 114 was killed before it finished (likely due to running out of memory)
[2025-09-14T09:25:10.959+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-09-14T09:25:48.683+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-14T12:39:25.522+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [queued]>
[2025-09-14T12:39:25.716+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [queued]>
[2025-09-14T12:39:25.724+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-14T12:39:25.920+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): train_model> on 2025-09-13 00:00:00+00:00
[2025-09-14T12:39:25.968+0000] {standard_task_runner.py:60} INFO - Started process 653 to run task
[2025-09-14T12:39:26.013+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'train_model', 'scheduled__2025-09-13T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpgotf3bh7']
[2025-09-14T12:39:26.063+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask train_model
[2025-09-14T12:39:26.512+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-13T00:00:00+00:00 [running]> on host 6003dd60b185
[2025-09-14T12:39:27.317+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-13T00:00:00+00:00'
[2025-09-14T12:39:27.944+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-apps:latest
[2025-09-14T12:40:55.779+0000] {docker.py:429} INFO - /app/src/data/clean_data.py:26: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  median_by_tenure = df_clean.groupby(pd.cut(df_clean['tenure'], bins=[0, 12, 24, 48, 72]))['total_charges'].median()
[2025-09-14T12:40:59.901+0000] {docker.py:429} INFO - === CUSTOMER CHURN PREDICTION TRAINING ===

1. Loading data...
Loaded 5000 rows and 14 columns

2. Cleaning data...
Starting data cleaning...
Removed 0 duplicate rows
Data cleaning completed
Removed 293 outliers from total_charges
Data cleaning completed. Final shape: (4707, 14)

3. Transforming data...
Starting data transformation...
Fitted encoder for gender
Fitted encoder for contract
Fitted encoder for internet_service
Fitted encoder for online_security
Fitted encoder for tech_support
Fitted encoder for streaming_tv
Fitted encoder for payment_method
Fitted encoder for paperless_billing
Train set: 3765 samples
Test set: 942 samples
All transformers saved to /app/Models/transformers.joblib
Data transformation completed

4. Training models...
Training logistic_regression...
[2025-09-14T12:41:21.182+0000] {job.py:213} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 187, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 308, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-09-14T12:42:12.027+0000] {job.py:221} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2025-09-14T13:01:46.320+0000] {local_task_job_runner.py:211} ERROR - Heartbeat time limit exceeded!
[2025-09-14T13:01:55.908+0000] {process_utils.py:131} INFO - Sending 15 to group 653. PIDs of all processes in the group: [653]
[2025-09-14T13:01:58.218+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 653
[2025-09-14T13:02:06.801+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-14T13:02:15.698+0000] {docker.py:521} INFO - Stopping docker container
[2025-09-14T13:02:58.439+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=653, name='airflow task ru', status='sleeping', started='12:39:25') did not respond to SIGTERM. Trying SIGKILL
[2025-09-14T13:02:59.503+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 653
[2025-09-14T13:02:59.635+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=653, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='12:39:25') (653) terminated with exit code -9
[2025-09-14T13:02:59.658+0000] {standard_task_runner.py:175} ERROR - Job 8 was killed before it finished (likely due to running out of memory)
